<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="PackageDetails.aspx.cs" Inherits="OnlineTourismManagement.PackageDetails" %>

<asp:Content ID="head" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <asp:GridView ID="GridPackageDetails" runat="server" AutoGenerateColumns="false" DataKeyNames="PackageId" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="PackageDetails_RowCancelingEdit" OnRowDeleting="PackageDetails_RowDeleting" OnRowEditing="PackageDetails_RowEditing" OnRowUpdating="PackageDetails_RowUpdating" CellSpacing="4" ShowFooter="true" align="Center">
        <Columns>
            <asp:TemplateField HeaderText="PackageId">
                <EditItemTemplate>
                    <asp:TextBox ID="textPackageId" runat="server" Text='<%# Container.DataItemIndex +1%>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPackageId" runat="server" Text='<%# Bind("packageId") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:LinkButton ID="linkInsert" runat="server" Text="Insert" OnClick="linkInsert_Click" ValidationGroup="validateInsert"></asp:LinkButton>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PackageName">
                <EditItemTemplate>
                    <asp:TextBox ID="textPackageName" runat="server" Text='<%# Bind("packageName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPackageName" runat="server" Text='<%# Bind("packageName") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtPackageName" runat="server"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvPackageName" runat="server" ControlToValidate="txtPackageName" ValidationGroup="validateInsert" ErrorMessage="Package name required" Style="color: red"></asp:RequiredFieldValidator>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PackageType">
                <EditItemTemplate>
                    <asp:TextBox ID="textPackageType" runat="server" Text='<%# Bind("packageType") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPackageType" runat="server" Text='<%# Bind("packageType") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtPackageType" runat="server"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvPackageType" runat="server" ControlToValidate="txtPackageType" ValidationGroup="validateInsert" ErrorMessage="Package type required" Style="color: red"></asp:RequiredFieldValidator>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PackagePrice">
                <EditItemTemplate>
                    <asp:TextBox ID="textPackagePrice" runat="server" Text='<%# Bind("packagePrice") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPackagePrice" runat="server" Text='<%# Bind("packagePrice") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtPackagePrice" runat="server"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="rfvPackagePrice" runat="server" ControlToValidate="txtPackagePrice" ValidationGroup="validateInsert" ErrorMessage="Package price required" Style="color: red"></asp:RequiredFieldValidator>
                </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
